//! `gen-ts`: emit the TypeScript bindings for the typed IPC command
//! surface from `eo-api`'s command manifest.
//!
//! The manifest carries every command's name, argument schemas, and
//! return schema, derived (via `schemars`) from the same serde
//! attributes that drive the wire serialisation, so the emitted types
//! cannot drift from the bytes. The output is committed
//! (`app/src/lib/api/commands.gen.ts`); `--check` regenerates in
//! memory and fails when the committed file is stale, the same
//! lock-step discipline the OpenAPI codegen had.

use std::path::PathBuf;

use serde_json::{Map, Value};

use crate::flag_value;

/// The committed output, relative to the repository root.
const OUTPUT: &str = "app/src/lib/api/commands.gen.ts";

pub fn run(args: &[String]) -> Result<i32, String> {
    let check = args.iter().any(|arg| arg == "--check");
    let root = repo_root(flag_value(args, "--root")?)?;
    let output_path = root.join(OUTPUT);

    let generated = generate()?;

    if check {
        let committed = std::fs::read_to_string(&output_path)
            .map_err(|e| format!("gen-ts: committed bindings unreadable at {OUTPUT}: {e}"))?
            .replace("\r\n", "\n");
        if committed != generated {
            return Err(format!(
                "gen-ts: {OUTPUT} is stale; regenerate with `cargo xtask gen-ts`"
            ));
        }
        println!("gen-ts: {OUTPUT} is current");
        return Ok(0);
    }

    std::fs::write(&output_path, &generated)
        .map_err(|e| format!("gen-ts: cannot write {OUTPUT}: {e}"))?;
    println!("gen-ts: wrote {OUTPUT}");
    Ok(0)
}

/// The repository root: `--root` when given, else derived from this
/// crate's manifest directory (`app/src-tauri/xtask`).
fn repo_root(explicit: Option<String>) -> Result<PathBuf, String> {
    if let Some(root) = explicit {
        return Ok(PathBuf::from(root));
    }
    Ok(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.."))
}

/// Generate the full bindings file, deterministically.
fn generate() -> Result<String, String> {
    let mut defs: Vec<(String, Value)> = Vec::new();
    let mut out = String::new();

    out.push_str(
        "// Generated by `cargo xtask gen-ts` from the eo-api command manifest.\n\
         // Do not edit; regenerate after changing the Rust DTOs or manifest.\n\
         // CI holds this file in lock-step (`cargo xtask gen-ts --check`).\n\n\
         import { invokeCommand } from './invoke';\n\n",
    );

    // The error contract's payload type, inlined from its own schema
    // (its variants are inline objects; the Rust name stays free for
    // the thrown class the client module exports).
    let error_schema = eo_api::manifest::error_schema();
    let error_body = union_or_type(&error_schema, &mut defs)?;
    out.push_str("/** The serialised error every command rejects with. */\n");
    out.push_str(&format!("export type ApiErrorPayload = {error_body};\n\n"));

    // The closed `kind` vocabulary, read off the same tagged-enum schema
    // so the thrown error class types its `kind` against the identical
    // source of truth as the payload. The const array is the runtime
    // guard for classifying a raw rejection at the transport boundary.
    let kinds = error_kinds(&error_schema)?;
    let kind_literals: Vec<String> = kinds.iter().map(|kind| format!("'{kind}'")).collect();
    out.push_str("/** The closed `kind` vocabulary of the error contract. */\n");
    out.push_str(&format!(
        "export type ApiErrorKind = {};\n\n",
        kind_literals.join(" | ")
    ));
    out.push_str("/** The error kinds as a runtime list, for guarding a raw rejection. */\n");
    out.push_str(&format!(
        "export const API_ERROR_KINDS: readonly ApiErrorKind[] = [{}];\n\n",
        kind_literals.join(", ")
    ));

    // Named types: walk every command schema, registering $defs and
    // titled object/enum roots under their names.
    let specs = eo_api::manifest::manifest();
    struct Command {
        name: String,
        args: Vec<(String, String)>,
        returns: Option<String>,
    }
    let mut commands: Vec<Command> = Vec::new();
    for spec in &specs {
        let mut args = Vec::new();
        for arg in &spec.args {
            collect_defs(&arg.schema, &mut defs)?;
            args.push((arg.name.to_string(), type_of(&arg.schema, &mut defs)?));
        }
        let returns = match &spec.returns {
            Some(schema) => {
                collect_defs(schema, &mut defs)?;
                Some(type_of(schema, &mut defs)?)
            }
            None => None,
        };
        commands.push(Command {
            name: spec.name.to_string(),
            args,
            returns,
        });
    }

    // Emit the named types, sorted for stable output.
    defs.sort_by(|a, b| a.0.cmp(&b.0));
    for (name, schema) in &defs {
        if let Some(description) = schema.get("description").and_then(Value::as_str) {
            out.push_str(&doc_comment(description));
        }
        // A string enum, or a oneOf/anyOf union (an enum whose variants
        // carry their own documentation, or an internally tagged enum),
        // is a type alias; only a plain object is an interface.
        if schema.get("enum").is_some()
            || schema.get("oneOf").is_some()
            || schema.get("anyOf").is_some()
        {
            let mut scratch = Vec::new();
            let body = union_or_type(schema, &mut scratch)?;
            out.push_str(&format!("export type {name} = {body};\n\n"));
        } else {
            let mut scratch = Vec::new();
            let body = object_body(schema, &mut scratch, 0)?;
            out.push_str(&format!("export interface {name} {body}\n\n"));
        }
    }

    // Emit the command wrappers, in manifest order.
    for command in &commands {
        let fn_name = camel(&command.name);
        let params: Vec<String> = command
            .args
            .iter()
            .map(|(name, ty)| format!("{}: {ty}", camel(name)))
            .collect();
        let keys: Vec<String> = command
            .args
            .iter()
            .map(|(name, _)| {
                let local = camel(name);
                if local == *name {
                    local
                } else {
                    format!("{name}: {local}")
                }
            })
            .collect();
        let ret = command.returns.as_deref().unwrap_or("void");
        let args_object = if keys.is_empty() {
            "{}".to_string()
        } else {
            format!("{{ {} }}", keys.join(", "))
        };
        out.push_str(&format!(
            "export async function {fn_name}({}): Promise<{ret}> {{\n\treturn invokeCommand('{}', {args_object});\n}}\n\n",
            params.join(", "),
            command.name,
        ));
    }

    // One trailing newline.
    while out.ends_with("\n\n") {
        out.pop();
    }
    Ok(out)
}

/// The error contract's `kind` values, in variant order: each tagged
/// variant carries its tag as a `const` (or single-member `enum`) on the
/// `kind` property.
fn error_kinds(schema: &Value) -> Result<Vec<String>, String> {
    let variants = schema
        .get("oneOf")
        .and_then(Value::as_array)
        .ok_or_else(|| "gen-ts: error schema is not a oneOf union".to_string())?;
    let mut kinds = Vec::with_capacity(variants.len());
    for variant in variants {
        let kind_schema = variant
            .get("properties")
            .and_then(|properties| properties.get("kind"))
            .ok_or_else(|| format!("gen-ts: error variant without a kind tag: {variant}"))?;
        let kind = kind_schema
            .get("const")
            .and_then(Value::as_str)
            .or_else(|| {
                kind_schema
                    .get("enum")
                    .and_then(Value::as_array)
                    .and_then(|values| values.first())
                    .and_then(Value::as_str)
            })
            .ok_or_else(|| format!("gen-ts: error variant kind is not a literal: {variant}"))?;
        kinds.push(kind.to_string());
    }
    Ok(kinds)
}

/// Register a schema's `$defs`, plus the titled object/enum root
/// itself, under their names; identical re-registrations are the
/// expected case (every command derives its own copy), a divergent one
/// is an error.
fn collect_defs(schema: &Value, defs: &mut Vec<(String, Value)>) -> Result<(), String> {
    if let Some(children) = schema.get("$defs").and_then(Value::as_object) {
        for (name, child) in children {
            register_def(name, child.clone(), defs)?;
        }
    }
    if let Some(title) = schema.get("title").and_then(Value::as_str) {
        let named_root = schema.get("type") == Some(&Value::String("object".into()))
            || schema.get("enum").is_some()
            || schema.get("oneOf").is_some();
        if named_root && is_pascal(title) {
            let mut body = schema.clone();
            if let Some(object) = body.as_object_mut() {
                object.remove("$schema");
                object.remove("$defs");
                object.remove("title");
            }
            register_def(title, body, defs)?;
        }
    }
    Ok(())
}

fn register_def(name: &str, body: Value, defs: &mut Vec<(String, Value)>) -> Result<(), String> {
    if let Some((_, existing)) = defs.iter().find(|(n, _)| n == name) {
        if *existing != body {
            return Err(format!(
                "gen-ts: type {name} derives two different schemas; \
                 rename one of the colliding Rust types"
            ));
        }
        return Ok(());
    }
    defs.push((name.to_string(), body));
    Ok(())
}

fn is_pascal(name: &str) -> bool {
    name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
        && name.chars().all(|c| c.is_ascii_alphanumeric())
}

/// The TypeScript type a schema denotes, referencing named types where
/// the schema does.
fn type_of(schema: &Value, defs: &mut Vec<(String, Value)>) -> Result<String, String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference
            .strip_prefix("#/$defs/")
            .ok_or_else(|| format!("gen-ts: unsupported $ref {reference}"))?;
        return Ok(name.to_string());
    }
    // A titled object/enum root reads as its registered name.
    if let Some(title) = schema.get("title").and_then(Value::as_str) {
        if is_pascal(title)
            && (schema.get("type") == Some(&Value::String("object".into()))
                || schema.get("enum").is_some())
        {
            return Ok(title.to_string());
        }
    }
    if schema.get("oneOf").is_some()
        || schema.get("anyOf").is_some()
        || schema.get("enum").is_some()
    {
        return union_or_type(schema, defs);
    }
    if let Some(constant) = schema.get("const") {
        return Ok(literal(constant));
    }
    match schema.get("type") {
        Some(Value::String(kind)) => scalar_or_composite(kind, schema, defs),
        Some(Value::Array(kinds)) => {
            let mut parts = Vec::new();
            for kind in kinds {
                let kind = kind
                    .as_str()
                    .ok_or_else(|| format!("gen-ts: non-string type entry in {schema}"))?;
                parts.push(scalar_or_composite(kind, schema, defs)?);
            }
            Ok(parts.join(" | "))
        }
        _ => Err(format!("gen-ts: unsupported schema shape: {schema}")),
    }
}

fn scalar_or_composite(
    kind: &str,
    schema: &Value,
    defs: &mut Vec<(String, Value)>,
) -> Result<String, String> {
    match kind {
        "string" => Ok("string".to_string()),
        "boolean" => Ok("boolean".to_string()),
        "integer" | "number" => Ok("number".to_string()),
        "null" => Ok("null".to_string()),
        "array" => {
            let items = schema
                .get("items")
                .ok_or_else(|| format!("gen-ts: array without items: {schema}"))?;
            let inner = type_of(items, defs)?;
            if inner.contains(' ') {
                Ok(format!("({inner})[]"))
            } else {
                Ok(format!("{inner}[]"))
            }
        }
        "object" => {
            // A map type (schemars renders `BTreeMap`/`HashMap` as an object
            // with `additionalProperties` and no `properties`) reads as
            // `Record<string, V>`, preserving the value type rather than
            // collapsing to `{}`. An object carrying its own `properties`
            // keeps its inline shape.
            if schema.get("properties").is_none() {
                match schema.get("additionalProperties") {
                    Some(Value::Bool(true)) => return Ok("Record<string, unknown>".to_string()),
                    Some(value) if value.as_bool() != Some(false) => {
                        return Ok(format!("Record<string, {}>", type_of(value, defs)?));
                    }
                    _ => {}
                }
            }
            object_body(schema, defs, 1)
        }
        other => Err(format!("gen-ts: unsupported type {other:?}")),
    }
}

/// A string-enum or oneOf union.
fn union_or_type(schema: &Value, defs: &mut Vec<(String, Value)>) -> Result<String, String> {
    if let Some(variants) = schema.get("enum").and_then(Value::as_array) {
        let parts: Vec<String> = variants.iter().map(literal).collect();
        return Ok(parts.join(" | "));
    }
    for key in ["oneOf", "anyOf"] {
        if let Some(variants) = schema.get(key).and_then(Value::as_array) {
            let mut parts = Vec::new();
            for variant in variants {
                parts.push(type_of(variant, defs)?);
            }
            return Ok(parts.join(" | "));
        }
    }
    type_of(schema, defs)
}

fn literal(value: &Value) -> String {
    match value {
        Value::String(s) => format!("'{s}'"),
        other => other.to_string(),
    }
}

/// An object schema's `{ ... }` body, fields in declaration order.
fn object_body(
    schema: &Value,
    defs: &mut Vec<(String, Value)>,
    depth: usize,
) -> Result<String, String> {
    let empty = Map::new();
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let indent = "\t".repeat(depth + 1);
    let closing = "\t".repeat(depth);
    let mut out = String::from("{\n");
    for (name, child) in properties {
        if let Some(description) = child.get("description").and_then(Value::as_str) {
            out.push_str(&format!(
                "{indent}/** {} */\n",
                description.replace('\n', " ")
            ));
        }
        let optional = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        let ty = type_of(child, defs)?;
        out.push_str(&format!("{indent}{name}{optional}: {ty};\n"));
    }
    out.push_str(&format!("{closing}}}"));
    Ok(out)
}

/// A JSDoc block from a schema description.
fn doc_comment(description: &str) -> String {
    let mut out = String::from("/**\n");
    for line in description.lines() {
        out.push_str(&format!(" * {line}\n"));
    }
    out.push_str(" */\n");
    out
}

/// snake_case to camelCase.
fn camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = false;
    for c in name.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_converts_snake_case() {
        assert_eq!(camel("equipment_library"), "equipmentLibrary");
        assert_eq!(camel("q"), "q");
        assert_eq!(camel("item_id"), "itemId");
    }

    #[test]
    fn map_typed_fields_emit_a_record_type() {
        // A `BTreeMap<String, f64>` field (object schema with
        // `additionalProperties`, no `properties`) reads as
        // `Record<string, number>`, not `{}`.
        let schema = serde_json::json!({
            "type": "object",
            "additionalProperties": { "type": "number" },
        });
        let mut defs = Vec::new();
        assert_eq!(
            type_of(&schema, &mut defs).unwrap(),
            "Record<string, number>"
        );

        // The analytics DTOs' ledger maps carry through to the emitted file.
        let generated = generate().expect("bindings generate");
        assert!(
            generated.contains("ledger: Record<string, number>"),
            "the ledger map field should emit a Record type"
        );
        assert!(
            generated.contains("ledgerGains: Record<string, number>"),
            "the timeline ledgerGains map field should emit a Record type"
        );
    }

    /// A named union (an enum whose variants carry documentation, or an
    /// internally tagged enum) is a type alias, never an empty interface
    /// the frontend could satisfy with anything.
    #[test]
    fn named_unions_emit_type_aliases() {
        let generated = generate().expect("bindings generate");
        assert!(generated.contains("export type ProtectionCostStatus = 'booked' | 'pending';"));
        assert!(generated.contains("export type ProtectionStream = {"));
        assert!(
            !generated.contains("{\n}\n"),
            "no named type may emit as an empty interface"
        );
    }

    #[test]
    fn the_bindings_generate_and_name_every_command() {
        let generated = generate().expect("bindings generate");
        for spec in eo_api::manifest::manifest() {
            assert!(
                generated.contains(&format!("'{}'", spec.name)),
                "{} missing from the generated bindings",
                spec.name
            );
        }
        assert!(generated.contains("export type ApiErrorPayload"));
    }

    #[test]
    fn the_error_kind_union_matches_the_error_contract() {
        let generated = generate().expect("bindings generate");
        assert!(
            generated.contains(
                "export type ApiErrorKind = 'badRequest' | 'notFound' | 'conflict' | 'internal' | 'unavailable';"
            ),
            "the error-kind union should carry the five tagged variants in declaration order"
        );
        assert!(generated.contains("export const API_ERROR_KINDS: readonly ApiErrorKind[]"));
    }
}
