"""Drift guard for the service coverage matrix.

``backend/testing/COVERAGE.md`` is generated by
``backend/scripts/coverage_matrix.py`` from the service modules, the test
tree, and the gate configuration in ``pyproject.toml``. This test
re-renders the matrix and asserts the tracked file matches, so adding a
service, a covering test, or changing a service's classification without
regenerating the matrix fails CI rather than letting the audit artefact go
stale. Regenerate with ``pytest --update-fingerprints`` (or by running the
generator directly) after reviewing the surfaced diff.
"""

from __future__ import annotations

import difflib

import pytest

from backend.scripts.coverage_matrix import OUTPUT, render_matrix


@pytest.fixture
def update_fingerprints(request) -> bool:
    """Re-export the backend-wide ``--update-fingerprints`` flag locally."""
    return bool(request.config.getoption("--update-fingerprints"))


def test_coverage_matrix_matches_generator(update_fingerprints: bool) -> None:
    """The tracked COVERAGE.md equals a fresh render of the generator."""
    rendered = render_matrix()

    if update_fingerprints:
        OUTPUT.write_text(rendered, encoding="utf-8")
        return

    assert OUTPUT.exists(), (
        f"coverage matrix missing at {OUTPUT}; "
        "rerun with --update-fingerprints to generate it."
    )
    # read_text normalises CRLF to LF, matching the generator's LF output, so
    # the comparison is on content rather than line-ending policy.
    on_disk = OUTPUT.read_text(encoding="utf-8")
    if on_disk == rendered:
        return

    diff = "".join(
        difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="COVERAGE.md (tracked)",
            tofile="COVERAGE.md (regenerated)",
            n=3,
        )
    )
    pytest.fail(
        "COVERAGE.md is stale versus backend/scripts/coverage_matrix.py. Diff:\n\n"
        + diff
        + "\n\nRerun `python backend/scripts/coverage_matrix.py` (or pytest "
        "--update-fingerprints) and review the change."
    )
