// The application command surface, written once. A callback macro: each
// consumer passes the macro that shapes the list for its purpose, so the
// build script's ACL permissions, the invoke handler in `lib.rs`, and the
// manifest parity test all read the same list. `typed` are the typed IPC
// commands in `commands` (in the eo-api manifest's order); `shell` are the
// shell's own window, capture, updater, and lifecycle commands, by path from
// the crate root.
macro_rules! app_command_surface {
    ($shape:ident) => {
        $shape! {
            typed: [
            equipment_search,
            equipment_library,
            equipment_add,
            equipment_update,
            equipment_delete,
            equipment_detail,
            protection_overview,
            protection_set_create,
            protection_set_update,
            protection_set_archive,
            protection_set_restore,
            protection_undo,
            protection_unrecorded_sessions,
            protection_session_status,
            protection_recording_candidates,
            protection_observation_confirm,
            protection_repair_confirm,
            protection_trade_terminal_scan,
            healing_outputs,
            healing_correction_tools,
            healing_correct,
            healing_correction_undo,
            consumable_doses,
            consumable_dose_start,
            consumable_dose_remove,
            consumable_dose_restore,
            consumable_session_doses,
            weapon_shots,
            weapon_unpriced_sessions,
            weapon_correction_weapons,
            weapon_assign,
            weapon_mark_effect_tick,
            weapon_assignment_undo,
            character_calibration,
            character_stats,
            character_skills,
            character_professions,
            character_prospect_options,
            character_prospect,
            character_profession_optimizer,
            character_path_optimizer,
            character_hp_optimizer,
            character_activity_recommender,
            settings_get,
            settings_overlay_position,
            settings_set_overlay_position,
            settings_update,
            codex_species,
            codex_species_ranks,
            codex_recommend,
            codex_meta_attributes,
            codex_calibrate,
            codex_claim,
            codex_unclaim,
            codex_meta_claim,
            codex_mastery_options,
            codex_mastery_claim,
            codex_mastery_unclaim,
            quests_list,
            quest_get,
            quest_create,
            quest_update,
            quest_delete,
            quest_start,
            quest_complete,
            quest_hand_in_begin,
            quest_hand_in_state,
            quest_hand_in_wait,
            quest_hand_in_cancel,
            quest_hand_in_confirm,
            quest_rewards_unresolved,
            quest_reward_review,
            quest_cancel,
            quests_mobs,
            quests_analytics,
            quest_families_list,
            quest_family_create,
            quest_family_update,
            quest_family_delete,
            session_definitions_list,
            session_definition_create,
            session_definition_update,
            session_definition_archive,
            session_definition_restore,
            tracking_definition_select,
            analytics_overview,
            analytics_hunting,
            analytics_harvest,
            analytics_hunting_activity,
            activity_stock,
            harvest_realised_markup,
            hunting_realised_markup,
            auction_listings,
            auction_listing_create,
            auction_listing_confirm,
            auction_listing_expire,
            stock_convert,
            stock_private_sale,
            stock_remove,
            stock_shrapnel_convert,
            activity_history,
            auction_sale_revert,
            auction_listing_undo,
            stock_conversion_undo,
            private_sale_undo,
            stock_removal_undo,
            ledger_list,
            ledger_summary,
            ledger_create,
            ledger_delete,
            ledger_presets_list,
            ledger_preset_create,
            ledger_preset_delete,
            inventory_list,
            inventory_create,
            inventory_update,
            inventory_delete,
            inventory_sell,
            inventory_sale_window_capture,
            inventory_sale_window_take_capture,
            inventory_draft_resolve,
            inventory_equipment_listing_create,
            inventory_equipment_trade,
            market_paste_preview,
            market_paste_commit,
            market_unit_price_set,
            market_overview,
            market_contribution_batch,
            market_auction_packet_threshold,
            market_break_even,
            market_mob_ranking,
            market_harvest_markups,
            market_hunt_markups,
            market_item_history,
            scan_status,
            scan_start,
            scan_capture,
            scan_cancel,
            scan_undo,
            scan_process,
            scan_accept,
            scan_reject,
            scan_pending,
            scan_spacebar_capture,
            tracking_sessions,
            tracking_session_detail,
            tracking_session_intervals,
            tracking_manual_mob_suggestions,
            tracking_snapshot,
            tracking_start,
            tracking_stop,
            tracking_weapon_decide,
            tracking_release_mob,
            tracking_manual_mob_lock,
            tracking_session_config,
            tracking_activity_options,
            tracking_activity_activate,
            tracking_activity_deactivate,
            tracking_reassign_session,
            tracking_rename_mob,
            tracking_restore_mob,
            tracking_loot_item_activate,
            tracking_loot_item_deactivate,
            tracking_armour_cost,
            tracking_repair_scan,
            tracking_session_delete,
            dev_metrics,
            dev_crash_reporting,
            dev_set_crash_reporting,
            dev_compact_database,
            dev_rebuild_projections,
            dev_auction_fee_research_start,
            dev_auction_fee_research_stop,
            dev_auction_fee_research_status,
            dev_auction_fee_research_capture,
            dev_auction_fee_research_overlay_status,
            planet_maps_list,
            map_pins_list,
            map_pins_viewport,
            map_pin_nearby,
            map_views_list,
            map_view_create,
            map_view_rename,
            map_view_delete,
            map_pin_create,
            map_pin_update,
            map_pin_delete,
            map_pin_cooldown,
            pin_configs_list,
            pin_config_create,
            pin_config_update,
            pin_config_delete,
            pin_config_reorder,
            maps_calibration_start,
            maps_calibration_cancel,
            maps_calibration_status,
            maps_scan_coordinates,
            navigation_snapshot,
            navigation_start,
            navigation_update_position,
            navigation_mark_visited,
            navigation_skip,
            navigation_resolve_harvest,
            navigation_undo,
            navigation_end,
            radar_calibration_start,
            radar_calibration_cancel,
            radar_calibration_status,
            radar_geometry,
            ],
            shell: [
            toggle_overlay,
            toggle_cartography_overlay,
            show_scan_overlay,
            show_sale_capture_overlay,
            hide_sale_capture_overlay,
            capture_sale_from_overlay,
            hide_scan_overlay,
            capture_png,
            planet_map_image,
            show_navigation_overlays,
            hide_navigation_overlays,
            begin_navigation_area_selection,
            updater::check_for_update,
            updater::download_update,
            updater::install_update,
            updater::get_update_channel,
            updater::set_update_channel,
            substrate::substrate_ready,
            substrate::restart_app,
            ],
        }
    };
}

macro_rules! command_names {
    (typed: [$($typed:ident),* $(,)?], shell: [$($($shell:ident)::+),* $(,)?] $(,)?) => {
        /// The typed IPC command names, in manifest order.
        #[allow(dead_code)]
        pub const TYPED_COMMANDS: &[&str] = &[$(stringify!($typed)),*];
        /// The shell command paths, as written (`module :: name`).
        const SHELL_COMMAND_PATHS: &[&str] = &[$(stringify!($($shell)::+)),*];
    };
}
app_command_surface!(command_names);

/// The complete application-command ACL catalogue: every typed and shell
/// command by its registered name. The build script generates one permission
/// per command and a trusted-window default set from it; narrow overlay
/// capabilities opt into only the commands they actually use.
#[allow(dead_code)]
pub fn app_commands() -> Vec<&'static str> {
    TYPED_COMMANDS
        .iter()
        .copied()
        .chain(
            SHELL_COMMAND_PATHS
                .iter()
                .map(|path| path.rsplit("::").next().unwrap_or(path).trim()),
        )
        .collect()
}

/// The capture overlay does one thing: read the sale window and take
/// itself off screen. It gets those commands, the fee-research capture
/// pair, and the startup readiness answer every window awaits.
pub const SALE_CAPTURE_COMMANDS: &[&str] = &[
    "capture_sale_from_overlay",
    "dev_auction_fee_research_capture",
    "dev_auction_fee_research_overlay_status",
    "hide_sale_capture_overlay",
    "substrate_ready",
];

pub const CARTOGRAPHY_COMMANDS: &[&str] = &[
    "map_pin_create",
    "map_pin_nearby",
    "map_views_list",
    "maps_scan_coordinates",
    "pin_configs_list",
    "planet_maps_list",
    "substrate_ready",
];

#[allow(dead_code)]
pub const NAVIGATION_COMMANDS: &[&str] = &[
    "begin_navigation_area_selection",
    "navigation_start",
    "maps_scan_coordinates",
    "navigation_snapshot",
    "navigation_update_position",
    "navigation_mark_visited",
    "navigation_skip",
    "navigation_resolve_harvest",
    "navigation_undo",
    "navigation_end",
    "hide_navigation_overlays",
    "substrate_ready",
];

#[allow(dead_code)]
pub const RADAR_GUIDANCE_COMMANDS: &[&str] =
    &["navigation_snapshot", "radar_geometry", "substrate_ready"];
