"""Build the synthetic soak-replay fixture bundle (committed, no real data).

Produces, beside this script:
  - ``starting_db.sqlite``: a current-schema DB carrying a starting skill
    calibration (so a chatlog gain computes a TT value and writes a new
    calibration point) plus one carried-forward codex claim and one quest
    claim (so the gate-2 codex/quest tables are non-empty and observed to be
    preserved across the replay).
  - ``chat_replay.log``: a scripted segment of skill-gain lines beginning on
    a fresh timestamp tick (the replay tick-boundary contract).
  - ``metadata.yaml``: provenance + the segment's instants.

The expected db_state golden (``expected_db_state.json``) is then generated by
``python -m backend.testing.real_session_replay --bundle <this dir> --update``
and ratified once (the ``skill_gains`` first-pin). Re-run this builder to
regenerate the synthetic inputs; the segment + seed are deterministic.

This is SYNTHETIC: it stands in for a real recorded bundle so the cross-check
runs in CI without committing any real account data.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from backend.db.app_database import AppDatabase
from backend.tracking.schema import init_tracking_tables

FIXTURE_DIR = Path(__file__).resolve().parent

# Deterministic seed instants (epoch seconds). Absolute values are irrelevant:
# the snapshot Normalizer symbolises them; only structure/order is compared.
SEED_TS = 1_717_200_000.0  # 2024-06-01T00:00:00Z, well before the segment


def build_starting_db(path: Path) -> None:
    if path.exists():
        path.unlink()
    app_db = AppDatabase(str(path))
    try:
        init_tracking_tables(app_db.conn)
        with app_db.lock:
            # A starting calibration: the chatlog gain for this skill computes
            # a TT value and appends a new calibration point.
            app_db.conn.execute(
                "INSERT INTO skill_calibrations (skill_name, level, source, scanned_at) "
                "VALUES (?, ?, 'scan', ?)",
                ("Laser Weaponry Technology", 100.0, SEED_TS),
            )
            # Carried-forward codex + quest claims (API-driven in life; here
            # they exercise gate-2 codex/quest coverage and must survive the
            # replay unchanged).
            app_db.conn.execute(
                "INSERT INTO codex_claims (species_name, rank, skill_name, ped_value, "
                "claimed_at, kind) VALUES (?, ?, ?, ?, ?, 'rank')",
                ("Atrox", 5, "Laser Weaponry Technology", 7.0, SEED_TS),
            )
            app_db.conn.execute(
                "INSERT INTO quest_claims (quest_id, quest_name, ped_value, claimed_at) "
                "VALUES (?, ?, ?, ?)",
                (1, "Iron Challenge: Atrox", 4.0, SEED_TS),
            )
            app_db.conn.commit()
    finally:
        app_db.close()


def build_segment(path: Path) -> None:
    # Two skill-gain lines on distinct ticks: the first skill has a starting
    # calibration (writes skill_gains + a new skill_calibrations row), the
    # second has none (writes skill_gains with a null TT value). Begins on a
    # fresh timestamp tick.
    lines = [
        "2026-06-01 12:00:05 [System] [] You have gained 1.5000 experience in your Laser Weaponry Technology skill\n",
        "2026-06-01 12:00:07 [System] [] You have gained 0.8000 experience in your Anatomy skill\n",
    ]
    path.write_text("".join(lines), encoding="utf-8", newline="\n")


def build_metadata(path: Path) -> None:
    doc = {
        "name": "soak_replay",
        "flavour": "synthetic",
        "description": (
            "Synthetic soak-replay fixture: skill-gain segment over a seeded "
            "starting DB, standing in for a real recorded session so the "
            "cross-check runs in CI without real data."
        ),
        "clock": {"start": "2026-06-01T12:00:00", "step_seconds": 1.0},
        "surfaces": [
            "skill_gains",
            "skill_calibrations",
            "codex_claims",
            "quest_claims",
        ],
    }
    path.write_text(
        yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )


def main() -> None:
    build_starting_db(FIXTURE_DIR / "starting_db.sqlite")
    build_segment(FIXTURE_DIR / "chat_replay.log")
    build_metadata(FIXTURE_DIR / "metadata.yaml")
    print(f"built synthetic soak-replay fixture inputs in {FIXTURE_DIR}")


if __name__ == "__main__":
    main()
